# Generated by `claude-task --init` — do not hand-edit.
# Re-run `claude-task --init --force` to regenerate from .devcontainer/claude-task.json.
FROM ghcr.io/sebastiankuehnau/claude-container:latest

USER root

# SDKMAN: single mechanism for the Java-version/vendor override and the
# build-tool install (Maven/Gradle aren't in the base image at all).
RUN curl -s "https://get.sdkman.io" | bash
ENV SDKMAN_DIR=/home/node/.sdkman
RUN bash -lc 'source "$SDKMAN_DIR/bin/sdkman-init.sh" \
    && CANDIDATE=$(sdk list java 2>/dev/null | grep -oE "25\.[0-9.]+-tem" | head -1) \
    && if [ -z "$CANDIDATE" ]; then echo "No SDKMAN candidate found for 25-tem" >&2; exit 1; fi \
    && sdk install java "$CANDIDATE"'
RUN bash -lc 'source "$SDKMAN_DIR/bin/sdkman-init.sh" && sdk install maven'
ENV JAVA_HOME=/home/node/.sdkman/candidates/java/current
ENV PATH="${JAVA_HOME}/bin:/home/node/.sdkman/candidates/maven/current/bin:/home/node/.sdkman/candidates/gradle/current/bin:${PATH}"
# MAVEN_OPTS file-locking is inherited from the base image — do not override.

USER node
